openapi: 3.0.1
info:
  title: VapeLife E-commerce API Documentation
  description: An E-commerce webapp for all your vaping needs
  version: 1.0.0
paths:
  /carts:
    post:
      summary: Create a new cart
      tags:
        - Cart
      responses:
        '200':
          description: Cart created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Cart ID
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        product:
                          type: string
                          description: Product ID
                        quantity:
                          type: integer
                          description: Quantity of the product
        '500':
          description: Internal server error
    get:
      summary: Get products in a cart
      tags:
        - Cart
      parameters:
        - in: query
          name: cid
          schema:
            type: string
          required: true
          description: Cart ID
      responses:
        '200':
          description: Products retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    product:
                      type: string
                      description: Product ID
                    quantity:
                      type: integer
                      description: Quantity of the product
        '404':
          description: Cart not found
        '500':
          description: Internal server error
  /carts/{cid}/products/{pid}:
    post:
      summary: Add a product to a cart
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: Cart ID
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: Product ID
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Quantity of the product
      responses:
        '200':
          description: Product added successfully to the cart
        '500':
          description: Internal server error
    delete:
      summary: Delete a product from a cart
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: Cart ID
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: Product ID
      responses:
        '200':
          description: Product deleted successfully from the cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Success status
                  message:
                    type: string
                    description: Success message
                  cart:
                    type: object
                    description: Updated cart details
        '500':
          description: Internal server error
  /carts/{cid}/empty:
    patch:
      summary: Empty a cart
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: Cart ID
      responses:
        '200':
          description: Cart emptied successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Success status
                  message:
                    type: string
                    description: Success message
                  newcart:
                    type: object
                    description: Updated cart details
        '500':
          description: Internal server error
  /carts/{cid}/purchase:
    post:
      summary: Checkout a cart
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: Cart ID
      responses:
        '200':
          description: Checkout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  unavailableProductIds:
                    type: array
                    items:
                      type: string
                      description: Product IDs that were unavailable
        '500':
          description: Internal server error
